### ISSUE TITLE
Plugin broken with recent machine agents

### ISSUE THREAD

**Issue by HououinKyouma8591** [Appdynamics/aws-rds-monitoring-extension#12]
Hi guys,

This plugin seems to no longer work since the log4j vulnerability updates, specifically machineagentversion 21.12.4.3218 for linux

Error is:

java.lang.NullPointerException:null
...
...
...
at com.singularity.ee.util.javaspecific.scheduler.ADFutureTasks$Sync.innerRunAndReset(ADFutureTask.java:335) [agent-21.1.0-2340.jar:?]
...
...

Can you guys please look into this?

**Comment by HououinKyouma8591** [comment]
Last confirmed version it worked with is 20.7.0.2694

**Comment by saxenaabhi142** [comment]
Hi @HououinKyouma8591,

The latest version 2.0.7 or the extension is compatible with machine agent 21.x versions. We suggest you to please build the latest version using java 8 and `mvn clean install` command and use the extension. Please reconfigure the extension from scratch and do not use any file from previous version of the extension. 

If you are still facing issues with the extension then kindly reach out to us at help@appdynamics.com so that we can analyse some documents and help you further with the issue.

**Comment by HououinKyouma8591** [comment]
That worked, thanks a lot
